apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wedo-demo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mohi445257/GitOps-DevOps-Assignment.git'
    path: 'deployments/dev'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
