name: ci-build-and-update-manifests

on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✅ allow pushing changes back

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/wedevs-devops-assignment:${{ github.sha }}

      - name: Update deployment manifest with new image tag
        env:
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/wedevs-devops-assignment
        run: |
          set -e
          FULL_IMAGE="${IMAGE_NAME}:${IMAGE_TAG}"
          echo "Updating dev deployment with image: $FULL_IMAGE"

          sed -i "s|__IMAGE__|$FULL_IMAGE|g" deployments/dev/deployment.yaml
          sed -i "s|__IMAGE_TAG__|$IMAGE_TAG|g" deployments/dev/deployment.yaml

          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add deployments/dev/deployment.yaml
          git commit -m "Update dev deployment to $FULL_IMAGE" || echo "No changes to commit"
          git push
